<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <RootNamespace>Swdm2.UiTestsDriver</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Swdm2.UiTests\Swdm2.UiTests.csproj" />
  </ItemGroup>

</Project>
