<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Swdm2.Core\Swdm2.Core.csproj" />
    <ProjectReference Include="..\Swdm2.Steam\Swdm2.Steam.csproj" />
    <ProjectReference Include="..\Swdm2.Downloads\Swdm2.Downloads.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
