<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="C:\Users\Lenovo\Desktop\程序设计\steam mod program\swdm2\src\Swdm2.Steam\Swdm2.Steam.csproj" />
  </ItemGroup>
</Project>
