<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF></PropertyGroup><ItemGroup><ProjectReference Include="C:\Users\Lenovo\Desktop\程序设计\steam mod program\swdm2\tests\Swdm2.UiTests\Swdm2.UiTests.csproj" /></ItemGroup></Project>
